Removing default proxy value
Removing default proxy value to avoid errors when not using a proxy:
```
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE3B3B02E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
```

Thanks!